[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "grow giraffe race polar excess rib glove evolve ride cart
 gaze castle bright gift express corn notice wire whale gun woman regular taste march"
